#!/bin/bash
#
# chkconfig: 35 90 12
# description: Foo server
#
# Get function from functions library
. /etc/init.d/functions

# Docker variables

CONTAINER_NAME=jenkins-master
CONTAINER_IMAGE=jenkins-master
CONTAINER_VOLUME_FROM=jenkins-data
DOCKER_RUN="docker run -d --volumes-from $CONTAINER_VOLUME_FROM -p 8000:8000 -p 80:8080 --name $CONTAINER_NAME $CONTAINER_IMAGE"
DOCKER_STOP="docker kill $CONTAINER_NAME"
DOCKER_RM="docker rm $CONTAINER_NAME"

# Start the service FOO
start() {
        echo -n "Starting $CONTAINER_NAME server: "

	$DOCKER_RUN > /dev/null 2>&1

        echo OK
}
# Restart the service FOO
stop() {

        echo -n "Stopping $CONTAINER_NAME server: "

	$DOCKER_STOP > /dev/null
	$DOCKER_RM > /dev/null

        echo

}
### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status FOO
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
exit 0
